"""update users table

Revision ID: 86cddd5541f4
Revises: ab366465b6f2
Create Date: 2026-02-22 14:38:08.661831
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86cddd5541f4'
down_revision = 'ab366465b6f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
