"""vacancies search history

Revision ID: adf5d47f9c60
Revises: b2c3d4e5f6a7
Create Date: 2026-03-21 11:48:15.782553
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adf5d47f9c60'
down_revision = 'b2c3d4e5f6a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vacancies_search_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('search_text', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute(sa.text('DROP INDEX IF EXISTS ix_companies_industry'))
    op.execute(sa.text('DROP INDEX IF EXISTS ix_companies_name'))
    op.execute(sa.text('DROP INDEX IF EXISTS ix_refresh_tokens_user_id'))
    op.execute(sa.text('DROP INDEX IF EXISTS ix_resumes_desired_role'))
    op.execute(sa.text('DROP INDEX IF EXISTS ix_vacancies_company_id'))
    op.execute(sa.text('DROP INDEX IF EXISTS ix_vacancies_is_active'))
    op.execute(sa.text('DROP INDEX IF EXISTS ix_vacancies_title'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_vacancies_title'), 'vacancies', ['title'], unique=False)
    op.create_index(op.f('ix_vacancies_is_active'), 'vacancies', ['is_active'], unique=False)
    op.create_index(op.f('ix_vacancies_company_id'), 'vacancies', ['company_id'], unique=False)
    op.create_index(op.f('ix_resumes_desired_role'), 'resumes', ['desired_role'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_index(op.f('ix_companies_industry'), 'companies', ['industry'], unique=False)
    op.drop_table('vacancies_search_history')
    # ### end Alembic commands ###
