on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    env:
        POSTGRES_DB: test_db
        POSTGRES_USER: test_user
        POSTGRES_PASSWORD: test_password
        POSTGRES_HOST: postgres
        POSTGRES_PORT: 5432

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start containers
        run: docker compose up -d --build


      - name: Run tests
        run: docker compose run --rm backend pytest

      - name: Stop containers
        if: always()
        run: docker compose down